// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ocpp_forwarder.proto

package ocppforwarder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum defining action listener should take based on server processing
type ResponseAction int32

const (
	ResponseAction_DO_NOTHING    ResponseAction = 0 // Server handled it, no OCPP response needed from listener
	ResponseAction_SEND_RESPONSE ResponseAction = 1 // Send the included response_payload back as CallResult
)

// Enum value maps for ResponseAction.
var (
	ResponseAction_name = map[int32]string{
		0: "DO_NOTHING",
		1: "SEND_RESPONSE",
	}
	ResponseAction_value = map[string]int32{
		"DO_NOTHING":    0,
		"SEND_RESPONSE": 1,
	}
)

func (x ResponseAction) Enum() *ResponseAction {
	p := new(ResponseAction)
	*p = x
	return p
}

func (x ResponseAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseAction) Descriptor() protoreflect.EnumDescriptor {
	return file_ocpp_forwarder_proto_enumTypes[0].Descriptor()
}

func (ResponseAction) Type() protoreflect.EnumType {
	return &file_ocpp_forwarder_proto_enumTypes[0]
}

func (x ResponseAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseAction.Descriptor instead.
func (ResponseAction) EnumDescriptor() ([]byte, []int) {
	return file_ocpp_forwarder_proto_rawDescGZIP(), []int{0}
}

// Result of a command sent to a charger
type CommandResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChargePointId     string                 `protobuf:"bytes,1,opt,name=charge_point_id,json=chargePointId,proto3" json:"charge_point_id,omitempty"`             // ID of the charger responding
	OriginalMessageId string                 `protobuf:"bytes,2,opt,name=original_message_id,json=originalMessageId,proto3" json:"original_message_id,omitempty"` // Message ID of the original SendCommand request
	Success           bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`                                               // True if CallResult received, false if CallError or timeout
	ResponsePayload   []byte                 `protobuf:"bytes,4,opt,name=response_payload,json=responsePayload,proto3" json:"response_payload,omitempty"`         // The JSON payload from the CallResult (if success=true)
	// Fields for CallError details (if success=false)
	ErrorCode        string `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // e.g., "GenericError"
	ErrorDescription string `protobuf:"bytes,6,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`
	ErrorDetails     []byte `protobuf:"bytes,7,opt,name=error_details,json=errorDetails,proto3" json:"error_details,omitempty"` // JSON object
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_ocpp_forwarder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_ocpp_forwarder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_ocpp_forwarder_proto_rawDescGZIP(), []int{0}
}

func (x *CommandResult) GetChargePointId() string {
	if x != nil {
		return x.ChargePointId
	}
	return ""
}

func (x *CommandResult) GetOriginalMessageId() string {
	if x != nil {
		return x.OriginalMessageId
	}
	return ""
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetResponsePayload() []byte {
	if x != nil {
		return x.ResponsePayload
	}
	return nil
}

func (x *CommandResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *CommandResult) GetErrorDescription() string {
	if x != nil {
		return x.ErrorDescription
	}
	return ""
}

func (x *CommandResult) GetErrorDetails() []byte {
	if x != nil {
		return x.ErrorDetails
	}
	return nil
}

// Response to the notification
type NotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_ocpp_forwarder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocpp_forwarder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_ocpp_forwarder_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

// The request message containing the raw OCPP message bytes.
type OcppMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChargePointId string                 `protobuf:"bytes,1,opt,name=charge_point_id,json=chargePointId,proto3" json:"charge_point_id,omitempty"` // Identifier of the originating charge point (e.g., from connection context)
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`               // Original MessageId from OCPP message (needed for CallResult)
	RawMessage    []byte                 `protobuf:"bytes,3,opt,name=raw_message,json=rawMessage,proto3" json:"raw_message,omitempty"`            // The original OCPP JSON message as bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OcppMessage) Reset() {
	*x = OcppMessage{}
	mi := &file_ocpp_forwarder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OcppMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OcppMessage) ProtoMessage() {}

func (x *OcppMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ocpp_forwarder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OcppMessage.ProtoReflect.Descriptor instead.
func (*OcppMessage) Descriptor() ([]byte, []int) {
	return file_ocpp_forwarder_proto_rawDescGZIP(), []int{2}
}

func (x *OcppMessage) GetChargePointId() string {
	if x != nil {
		return x.ChargePointId
	}
	return ""
}

func (x *OcppMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *OcppMessage) GetRawMessage() []byte {
	if x != nil {
		return x.RawMessage
	}
	return nil
}

// The response message indicating success/failure and potential response payload.
type ForwardResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ProcessedSuccessfully bool                   `protobuf:"varint,1,opt,name=processed_successfully,json=processedSuccessfully,proto3" json:"processed_successfully,omitempty"`              // Did the server process the request without internal error?
	ResponseAction        ResponseAction         `protobuf:"varint,2,opt,name=response_action,json=responseAction,proto3,enum=ocppforwarder.ResponseAction" json:"response_action,omitempty"` // What should the listener do?
	ResponsePayload       []byte                 `protobuf:"bytes,3,opt,name=response_payload,json=responsePayload,proto3" json:"response_payload,omitempty"`                                 // The JSON payload to send back in the CallResult (if response_action=SEND_RESPONSE)
	ErrorMessage          string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                                          // Optional message (e.g., server processing error details)
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ForwardResponse) Reset() {
	*x = ForwardResponse{}
	mi := &file_ocpp_forwarder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResponse) ProtoMessage() {}

func (x *ForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocpp_forwarder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResponse.ProtoReflect.Descriptor instead.
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return file_ocpp_forwarder_proto_rawDescGZIP(), []int{3}
}

func (x *ForwardResponse) GetProcessedSuccessfully() bool {
	if x != nil {
		return x.ProcessedSuccessfully
	}
	return false
}

func (x *ForwardResponse) GetResponseAction() ResponseAction {
	if x != nil {
		return x.ResponseAction
	}
	return ResponseAction_DO_NOTHING
}

func (x *ForwardResponse) GetResponsePayload() []byte {
	if x != nil {
		return x.ResponsePayload
	}
	return nil
}

func (x *ForwardResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_ocpp_forwarder_proto protoreflect.FileDescriptor

const file_ocpp_forwarder_proto_rawDesc = "" +
	"\n" +
	"\x14ocpp_forwarder.proto\x12\rocppforwarder\"\x9d\x02\n" +
	"\rCommandResult\x12&\n" +
	"\x0fcharge_point_id\x18\x01 \x01(\tR\rchargePointId\x12.\n" +
	"\x13original_message_id\x18\x02 \x01(\tR\x11originalMessageId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12)\n" +
	"\x10response_payload\x18\x04 \x01(\fR\x0fresponsePayload\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\x12+\n" +
	"\x11error_description\x18\x06 \x01(\tR\x10errorDescription\x12#\n" +
	"\rerror_details\x18\a \x01(\fR\ferrorDetails\":\n" +
	"\x14NotificationResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"u\n" +
	"\vOcppMessage\x12&\n" +
	"\x0fcharge_point_id\x18\x01 \x01(\tR\rchargePointId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1f\n" +
	"\vraw_message\x18\x03 \x01(\fR\n" +
	"rawMessage\"\xe0\x01\n" +
	"\x0fForwardResponse\x125\n" +
	"\x16processed_successfully\x18\x01 \x01(\bR\x15processedSuccessfully\x12F\n" +
	"\x0fresponse_action\x18\x02 \x01(\x0e2\x1d.ocppforwarder.ResponseActionR\x0eresponseAction\x12)\n" +
	"\x10response_payload\x18\x03 \x01(\fR\x0fresponsePayload\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage*3\n" +
	"\x0eResponseAction\x12\x0e\n" +
	"\n" +
	"DO_NOTHING\x10\x00\x12\x11\n" +
	"\rSEND_RESPONSE\x10\x012\xbb\x01\n" +
	"\rOcppForwarder\x12N\n" +
	"\x0eForwardMessage\x12\x1a.ocppforwarder.OcppMessage\x1a\x1e.ocppforwarder.ForwardResponse\"\x00\x12Z\n" +
	"\x13NotifyCommandResult\x12\x1c.ocppforwarder.CommandResult\x1a#.ocppforwarder.NotificationResponse\"\x00B4Z2github.com/waltu/shining-light/proto/ocppforwarderb\x06proto3"

var (
	file_ocpp_forwarder_proto_rawDescOnce sync.Once
	file_ocpp_forwarder_proto_rawDescData []byte
)

func file_ocpp_forwarder_proto_rawDescGZIP() []byte {
	file_ocpp_forwarder_proto_rawDescOnce.Do(func() {
		file_ocpp_forwarder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ocpp_forwarder_proto_rawDesc), len(file_ocpp_forwarder_proto_rawDesc)))
	})
	return file_ocpp_forwarder_proto_rawDescData
}

var file_ocpp_forwarder_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ocpp_forwarder_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ocpp_forwarder_proto_goTypes = []any{
	(ResponseAction)(0),          // 0: ocppforwarder.ResponseAction
	(*CommandResult)(nil),        // 1: ocppforwarder.CommandResult
	(*NotificationResponse)(nil), // 2: ocppforwarder.NotificationResponse
	(*OcppMessage)(nil),          // 3: ocppforwarder.OcppMessage
	(*ForwardResponse)(nil),      // 4: ocppforwarder.ForwardResponse
}
var file_ocpp_forwarder_proto_depIdxs = []int32{
	0, // 0: ocppforwarder.ForwardResponse.response_action:type_name -> ocppforwarder.ResponseAction
	3, // 1: ocppforwarder.OcppForwarder.ForwardMessage:input_type -> ocppforwarder.OcppMessage
	1, // 2: ocppforwarder.OcppForwarder.NotifyCommandResult:input_type -> ocppforwarder.CommandResult
	4, // 3: ocppforwarder.OcppForwarder.ForwardMessage:output_type -> ocppforwarder.ForwardResponse
	2, // 4: ocppforwarder.OcppForwarder.NotifyCommandResult:output_type -> ocppforwarder.NotificationResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ocpp_forwarder_proto_init() }
func file_ocpp_forwarder_proto_init() {
	if File_ocpp_forwarder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocpp_forwarder_proto_rawDesc), len(file_ocpp_forwarder_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ocpp_forwarder_proto_goTypes,
		DependencyIndexes: file_ocpp_forwarder_proto_depIdxs,
		EnumInfos:         file_ocpp_forwarder_proto_enumTypes,
		MessageInfos:      file_ocpp_forwarder_proto_msgTypes,
	}.Build()
	File_ocpp_forwarder_proto = out.File
	file_ocpp_forwarder_proto_goTypes = nil
	file_ocpp_forwarder_proto_depIdxs = nil
}
