// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ocpp-16-json/proto/ocpp_forwarder.proto

package ocppforwarder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the raw OCPP message bytes.
type OcppMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChargePointId string                 `protobuf:"bytes,1,opt,name=charge_point_id,json=chargePointId,proto3" json:"charge_point_id,omitempty"` // Identifier of the originating charge point (e.g., from connection context)
	RawMessage    []byte                 `protobuf:"bytes,2,opt,name=raw_message,json=rawMessage,proto3" json:"raw_message,omitempty"`            // The original OCPP JSON message as bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OcppMessage) Reset() {
	*x = OcppMessage{}
	mi := &file_ocpp_16_json_proto_ocpp_forwarder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OcppMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OcppMessage) ProtoMessage() {}

func (x *OcppMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ocpp_16_json_proto_ocpp_forwarder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OcppMessage.ProtoReflect.Descriptor instead.
func (*OcppMessage) Descriptor() ([]byte, []int) {
	return file_ocpp_16_json_proto_ocpp_forwarder_proto_rawDescGZIP(), []int{0}
}

func (x *OcppMessage) GetChargePointId() string {
	if x != nil {
		return x.ChargePointId
	}
	return ""
}

func (x *OcppMessage) GetRawMessage() []byte {
	if x != nil {
		return x.RawMessage
	}
	return nil
}

// The response message indicating success or failure.
type ForwardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Optional message (e.g., error details)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardResponse) Reset() {
	*x = ForwardResponse{}
	mi := &file_ocpp_16_json_proto_ocpp_forwarder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResponse) ProtoMessage() {}

func (x *ForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocpp_16_json_proto_ocpp_forwarder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResponse.ProtoReflect.Descriptor instead.
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return file_ocpp_16_json_proto_ocpp_forwarder_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForwardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ocpp_16_json_proto_ocpp_forwarder_proto protoreflect.FileDescriptor

const file_ocpp_16_json_proto_ocpp_forwarder_proto_rawDesc = "" +
	"\n" +
	"'ocpp-16-json/proto/ocpp_forwarder.proto\x12\rocppforwarder\"V\n" +
	"\vOcppMessage\x12&\n" +
	"\x0fcharge_point_id\x18\x01 \x01(\tR\rchargePointId\x12\x1f\n" +
	"\vraw_message\x18\x02 \x01(\fR\n" +
	"rawMessage\"E\n" +
	"\x0fForwardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2_\n" +
	"\rOcppForwarder\x12N\n" +
	"\x0eForwardMessage\x12\x1a.ocppforwarder.OcppMessage\x1a\x1e.ocppforwarder.ForwardResponse\"\x00B4Z2github.com/waltu/shining-light/proto/ocppforwarderb\x06proto3"

var (
	file_ocpp_16_json_proto_ocpp_forwarder_proto_rawDescOnce sync.Once
	file_ocpp_16_json_proto_ocpp_forwarder_proto_rawDescData []byte
)

func file_ocpp_16_json_proto_ocpp_forwarder_proto_rawDescGZIP() []byte {
	file_ocpp_16_json_proto_ocpp_forwarder_proto_rawDescOnce.Do(func() {
		file_ocpp_16_json_proto_ocpp_forwarder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ocpp_16_json_proto_ocpp_forwarder_proto_rawDesc), len(file_ocpp_16_json_proto_ocpp_forwarder_proto_rawDesc)))
	})
	return file_ocpp_16_json_proto_ocpp_forwarder_proto_rawDescData
}

var file_ocpp_16_json_proto_ocpp_forwarder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ocpp_16_json_proto_ocpp_forwarder_proto_goTypes = []any{
	(*OcppMessage)(nil),     // 0: ocppforwarder.OcppMessage
	(*ForwardResponse)(nil), // 1: ocppforwarder.ForwardResponse
}
var file_ocpp_16_json_proto_ocpp_forwarder_proto_depIdxs = []int32{
	0, // 0: ocppforwarder.OcppForwarder.ForwardMessage:input_type -> ocppforwarder.OcppMessage
	1, // 1: ocppforwarder.OcppForwarder.ForwardMessage:output_type -> ocppforwarder.ForwardResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ocpp_16_json_proto_ocpp_forwarder_proto_init() }
func file_ocpp_16_json_proto_ocpp_forwarder_proto_init() {
	if File_ocpp_16_json_proto_ocpp_forwarder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocpp_16_json_proto_ocpp_forwarder_proto_rawDesc), len(file_ocpp_16_json_proto_ocpp_forwarder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ocpp_16_json_proto_ocpp_forwarder_proto_goTypes,
		DependencyIndexes: file_ocpp_16_json_proto_ocpp_forwarder_proto_depIdxs,
		MessageInfos:      file_ocpp_16_json_proto_ocpp_forwarder_proto_msgTypes,
	}.Build()
	File_ocpp_16_json_proto_ocpp_forwarder_proto = out.File
	file_ocpp_16_json_proto_ocpp_forwarder_proto_goTypes = nil
	file_ocpp_16_json_proto_ocpp_forwarder_proto_depIdxs = nil
}
